### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by alxrguz** [SR2k/homebridge-yeelight-screen-bar-pro#2]
Hello, tell me, is the project abandoned at the moment?)

**Comment by Marfre888** [comment]
@SR2k Also following this project.. any news on it?

**Comment by zhangyq527** [comment]
Also following this project.. any news on it?

**Comment by alxrguz** [comment]
@SR2k A simple answer from the series is enough for us: "I will not be engaged in the project" so that we do not feel hopes)

**Comment by SR2k** [comment]
@alxrguz @Marfre888 Sorry guys. Stucked with a company project. I'll add a readme this weekend.

**Comment by alxrguz** [comment]
Больше спасибо за обратную связь!

**Comment by alxrguz** [comment]
Thank you very much for your feedback!

**Comment by SR2k** [comment]
[README](https://github.com/SR2k/homebridge-yeelight-screen-bar-pro/blob/master/README.md) added.

**Comment by alxrguz** [comment]
@SR2k thank you

**Comment by Marfre888** [comment]
@alxrguz I haven't gotten my Yeelight Screen Bar yet. Can you control both the backlight and front light?

**Comment by SR2k** [comment]
@Marfre888 This plugin works for Yeelight Screen Bar Pro only.

And if you refer to the lights for the bar, you can control both of the lights using scenes of the Apple Home app. Also, the MiHome app has an option for controlling the power of two lights together.

**Comment by Marfre888** [comment]
Yes, I got the Screen Bar Pro.

But I read on the ‘Homebridge-yeelight-wifi’ project, that it discovers the screen bar pro, but it’s not supported correctly. It only has access to control the front monitor light.

I was wondering since you wrote this plugin for the Screen Bar, if you have managed to get control for both the front and the back lights on the bar.

**Comment by SR2k** [comment]
@Marfre888 I see. The answer is yes. You can control both the front and the backlights on the bar using this plugin.

This plugin uses the MIIO protocol to control the screen bar. Theoretically, we can map anything you can use in the MiHome app.

`homebridge-yeelight-wifi` uses Yeelight protocol to control the light, which is a more general method for all of the Yeelight lightings, which might lead to loss of certain functionality.
