### ISSUE TITLE
Will this plugin support Yeelight screen bar standard edition?

### ISSUE THREAD

**Issue by haoyouab** [SR2k/homebridge-yeelight-screen-bar-pro#3]
I have a screen bar without a 'pro' suffix. Is this plugin working for this model?

**Comment by SR2k** [comment]
I have tested it with the Pro version only. If those two model shares the same MiIO protocol, it might work.
Since I haven't got a standard version, you might need to try it yourself.

**Comment by SR2k** [comment]
Closing.

**Comment by haoyouab** [comment]
JFYI I have tested on standard edition and it's supported well. Perhaps you can add it in the support list.

**Comment by SR2k** [comment]
@ZhibinLiIntel Cool! I'll add it to readme.
